spring:
  application:
    name: worldcup-betting-app
  
  # Cấu hình Database kết nối tới PostgreSQL container chạy bằng Docker Compose.
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/betdb}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Cấu hình Token API Lịch thi đấu bóng đá từ football-data.org
football-api:
  token: "b462b4d4b35c4b5185c165f6782f37e4"
  base-url: "https://api.football-data.org/v4"

# Cấu hình JWT cho xác thực người dùng
jwt:
  secret: "3c968a3b576825595679261a8684711867156942065842831089201948723049" # Base64 hoặc chuỗi bí mật tối thiểu 256 bits
  expiration-ms: 864000000 # 10 ngày

# Cấu hình VietQR
vietqr:
  client-id: ${VIETQR_CLIENT_ID:4157ce1b-a11e-49e8-a323-37b9d0057135}
  api-key: ${VIETQR_API_KEY:746178d5-18de-4e19-b041-0844765f25d6}
  base-url: ${VIETQR_BASE_URL:https://api.vietqr.io/v2/generate}
  account-no: ${VIETQR_ACCOUNT_NO:0798128201}
  account-name: ${VIETQR_ACCOUNT_NAME:Ha Minh Nhat}
  acq-id: ${VIETQR_ACQ_ID:546034}

gmail:
  username: ${GMAIL_USERNAME:hanhat123123@gmail.com}
  password: ${GMAIL_PASSWORD:tarqlmwvymkiqnat}
  host: ${GMAIL_HOST:imap.gmail.com}
  port: ${GMAIL_PORT:993}
  protocol: ${GMAIL_PROTOCOL:imaps}


